const APPS_CONFIG = [
  {
    id: "resume-window",
    title: "Resume",
    icon: "https://win98icons.alexmeub.com/icons/png/notepad-0.png",
    label: "Resume",
    type: "fetch",
    contentUrl: "apps/resume/window.html",
    width: "340px",
    top: "60px",
    left: "120px",
    autoOpen: true,
    showOnDesktop: true,   // Display icon on desktop
    showInStartMenu: true  // Display item in start menu
  },
  {
    id: "clues-window",
    title: "MISSION_BRIEFING",
    icon: "https://win98icons.alexmeub.com/icons/png/search_file-2.png",
    label: "MISSION_BRIEFING",
    type: "fetch",
    contentUrl: "apps/briefing/step1.html",
    width: "340px",
    top: "140px",
    left: "200px",
    autoOpen: true,
    showOnDesktop: true,
    showInStartMenu: true
  },
  {
    id: "browser-window",
    title: "Internet Explorer - Start Page",
    icon: "assets/images/internet_explorer.png",
    label: "Internet Explorer",
    type: "browser",
    startPage: "apps/browser/start_page.html",
    width: "680px",
    height: "500px",
    top: "80px",
    left: "100px",
    autoOpen: false,
    showOnDesktop: true,
    showInStartMenu: true
  },
  {
    id: "calendar-window",
    title: "Calendar - Personal Agenda",
    icon: "https://win98icons.alexmeub.com/icons/png/calendar-0.png",
    label: "Calendar",
    type: "fetch",
    contentUrl: "apps/calendar/window.html",
    width: "320px",
    top: "120px",
    left: "180px",
    autoOpen: false,
    showOnDesktop: false,
    showInStartMenu: false
  },
  {
    id: "vault-window",
    title: "PROJECT_VAULT.exe - Encrypted",
    icon: "https://win98icons.alexmeub.com/icons/png/key_padlock-0.png",
    label: "Vault.exe",
    type: "fetch",
    contentUrl: "apps/vault/window.html",
    width: "360px",
    top: "100px",
    left: "240px",
    autoOpen: false,
    showOnDesktop: true,
    showInStartMenu: true
  },
  {
    id: "cmd-window",
    title: "Command Prompt",
    icon: "https://win98icons.alexmeub.com/icons/png/console_prompt-0.png",
    label: "Command Prompt",
    type: "fetch",
    contentUrl: "apps/cmd/window.html",
    width: "480px",
    top: "140px",
    left: "140px",
    autoOpen: false,
    showOnDesktop: true,
    showInStartMenu: true
  },
  {
    id: "control-panel-window",
    title: "Control Panel - Administrator Mode",
    icon: "https://win98icons.alexmeub.com/icons/png/control_panel-0.png",
    label: "Control Panel",
    type: "fetch",
    contentUrl: "apps/control_panel/main.html",
    width: "630px",
    height: "450px",
    top: "70px",
    left: "140px",
    autoOpen: false,
    showOnDesktop: false,
    showInStartMenu: false
  },
  {
    id: 'achievements-window',
    title: 'Achievements',
    icon: 'https://win98icons.alexmeub.com/icons/png/certificate-0.png',
    label: "Achievements",
    contentUrl: 'apps/achievements/main.html',
    width: '420px',
    height: '425px',
    top: '80px',
    left: '120px',
    autoOpen: false,
    showOnDesktop: true,
    showInStartMenu: true
  },
    {
    id: 'recycle-bin-window',
    title: 'Recycle Bin',
    icon: 'https://win98icons.alexmeub.com/icons/png/recycle_bin_full-0.png',
    label: "Recycle Bin",
    contentUrl: 'apps/recycle_bin/main.html',
    width: '480px',
    height: '350px',
    top: '90px',
    left: '140px',
    autoOpen: false,
    showOnDesktop: true,
    showInStartMenu: true
  },
  {
    id: 'file-explorer-window',
    title: 'File Explorer',
    icon: 'https://win98icons.alexmeub.com/icons/png/directory_closed-0.png',
    label: "Files",
    contentUrl: 'apps/file_explorer/main.html',
    width: '520px',
    height: '380px',
    top: '70px',
    left: '110px',
    autoOpen: false,
    showOnDesktop: true,
    showInStartMenu: true
  },
  {
    id: 'notepad-app',
    title: 'Notepad',
    icon: 'https://win98icons.alexmeub.com/icons/png/notepad-0.png',
    label: "Notes",
    action: () => window.openNotepad('Untitled - Notepad', ''),
    autoOpen: false,
    showOnDesktop: true,
    showInStartMenu: true
  },
  {
    id: "mail-window",
    title: "Hotmail",
    icon: "https://win98icons.alexmeub.com/icons/png/envelope_closed-0.png",
    label: "Hotmail",
    type: "fetch",
    contentUrl: "apps/mail/main.html",
    width: "800px",
    height: "430px",
    top: "80px",
    left: "150px",
    autoOpen: false,
    showOnDesktop: false,   // Hidden until downloaded
    showInStartMenu: false  // Hidden until downloaded
  },
  {
    id: 'calculator-window',
    title: 'Calculator',
    icon: 'https://win98icons.alexmeub.com/icons/png/calculator-0.png',
    contentUrl: 'apps/calculator/main.html',
    width: '360px',
    height: '240px',
    top: '100px',
    left: '300px',
    showOnDesktop: true,
    showInStartMenu: true
  },
  {
    id: 'paint-window',
    title: 'Paint',
    icon: 'https://win98icons.alexmeub.com/icons/png/paint_file-3.png',
    contentUrl: 'apps/paint/main.html',
    width: '360px',
    height: '370px',
    top: '90px',
    left: '280px',
    showOnDesktop: true,
    showInStartMenu: true
  },
  {
    id: 'minesweeper-window',
    title: 'Minesweeper',
    icon: 'https://win98icons.alexmeub.com/icons/png/minesweeper-0.png',
    contentUrl: 'apps/minesweeper/main.html',
    width: '240px',
    height: '260px',
    top: '110px',
    left: '350px',
    showOnDesktop: true,
    showInStartMenu: true
  }
];